### PR TITLE
fix the code about Memory leak on BruteCollisionDetection

### PR DESCRIPTION
**Pull request by cshyeon**
Hi, I added 'collisionStay' event to BruteCollisionDetection.js
This will help to identify whether or not to remain in collision.

### CODE REVIEW

**Comment by namel** [comment]
Is it possible to do this a little different?  I assume the list of collisions is very small.  So at the beginning of `detect()`, simply go over all the collisions, and if either `id1` or `id2` are not in `Object.keys(objects)` then delete that collision.

**Comment by OpherV** [comment]
I feel as if this might not be an ideal architecture. Emitting so many `collisionStay` events will actually degrade performance with the overhead involved in emitting them for every collision on every game step. The majority of the time you're not actually using these, so it makes more sense to actively query only the colliding pairs you do care about.

**Comment by cshyeon** [comment]
Thanks, code about Memory leak was modified according to namel's opinion
also removed the "collisionStay" event temporarily

**Comment by namel** [comment]
Thanks !

**Pull request merged**
