### PR TITLE
add support for using lance-gg as a node module

### PR DESCRIPTION
**Pull request by andrewkolos**
In reference to #90.

With this change Lance, projects can access lance with a simpler import syntax w/o any special build.

Exmaples:
`import * as Lance from 'lance-gg'`
`const Lance = require('lance-gg')`
`import { <specific members here> } from 'lance-gg'`

### Export scheme, Alternatives

The scheme set up here exposes all members at the top level. That is, any Lance member can at accessed with `Lance.<member name>` (e.g. `Lance.THREERenderer`). See `src/index.js`. I chose this since this is what I have personally seen most often in the world of node. Projects that tend to categorize members into different modules tend to use separate npm packages altogether to accomplish this ([Angular](https://github.com/angular/angular) is an example: e.g. `@angular/core` and `@angular/http`).

The alternative is [something else like this](https://hastebin.com/ifupayuzux.coffeescript), which organizes things into what you could think of as namespaces.

For either setup, `src/index.js` could be [written using ES6 syntax](https://hastebin.com/rijesumoho.js). I chose not to opt for ES6 syntax since node does not support it and would have to be transpiled to the format I'm using regardless. Also, I didn't know how to accomplish making `AFrameRenderer` into a getter so that it is lazily resolved (necessary since `AFrameRenderer` depends on `THREE` being declared but does not do so). I *think* the asynchronous nature of ES6 import/export syntax could handle this for us, but we lose the asynchronous nature of it when we transpile down into ES5.

### Drawbacks

When one `require`s Lance, All of Lance's code needs to be loaded into memory from disk (excluding `AFrameRenderer` since its `require` is wrapped in a getter). This could result in unnecessary of loading of components that are not used. The few libraries I've seen tend to go ahead and load everything that could be needed when the package library is imported, while some modularlize things into different modules, like Angular. Everything could be wrapped in getters [as discussed here](http://jbavari.github.io/blog/2015/08/25/lazy-loading-your-node-modules/), but those using the syntax `import * as Lance from 'lance-gg'` could run into slowdowns when they first access `Lance` members since that member's code file would need to be loaded into memory via the `require` statement, which I imagine is why I have not seen something like this done very often.

### Testing

[This repo](https://github.com/andrewkolos/lance-gg-as-node-module-test) can be used to test this change.

I recommend double checking to make sure I did not forget to export some classes/members.

### CODE REVIEW

**Comment by namel** [comment]
Hi - I am trying out the side-repo with spaaace, if all works smoothly I will merge.

**Comment by namel** [comment]
I'm trying to see what a game like [spaaace](https://github.com/lance-gg/spaaace) would look like with the new import mechanism.  So I changed the lance-gg dependency to point to your lance repository, under the branch `feature/support-use-as-npm-module`.

It doesn't seem to break anything (since webpack points the lance alias directly to the es5 sub-directory), but when I try to use the new syntax I get errors.  For example, I changed:

    import SimplePhysicsEngine from 'lance/physics/SimplePhysicsEngine';

to 

    import { SimplePhysicsEngine } from 'lance'; 

The error is: 
```
ERROR in ../andrew-lance/es5/ServerEngine.js
Module not found: Error: Can't resolve 'fs' in '/mnt/d/bash/andrew-lance/es5'
 @ ../andrew-lance/es5/ServerEngine.js 17:10-23
 @ ../andrew-lance/es5/index.js
 @ ./src/common/SpaaaceGameEngine.js
 @ ./src/client/clientMain.js
```

this fails, I assume because spaaace webpack tries to transpile server code with babel.  The fs package should not be part of the client code.  The `ServerEngine` class should not be part of the webpack bundle.  So we need a way to avoid loading all of the classes.

**Comment by andrewkolos** [comment]
Hello again. Looks like this change isn't going to work. Even if it did, sending server code and unused client code (like entire rendering engines) to the client would be silly. If we still want to clean up the import paths to get rid of the `src`, I think this will have to be done by moving all the source files to the top level of npm package either prepublish or postinstall. Regardless, I think this would have to be a change that waits until the next major version (unless we copy the files to the top level rather than move them there, so that they exist both in `src` and also at the top level, but that's kinda messy).

Going to close this. Feel free to reach out here or with a DM on the Slack if you have questions.

**Comment by andrewkolos** [comment]
Looks like Webpack 2+ supports tree-shaking on its dependencies, though ES6 syntax is required ([reference SO post](https://stackoverflow.com/questions/47663486/webpack-3-babel-and-tree-shaking-not-working). Looks like babel 7 is required to have this work by default though? Don't think this solves anything, but could be useful knowledge later on.

**Comment by OpherV** [comment]
Interesting, I feel like tree shaking is definitely a good direction. 
I also thought about checking whether [rollup](https://github.com/rollup/rollup) can provide benefit for packing Lance. The consensus as I understand it is that it's "better for libraries"

**Comment by namel** [comment]
I also think rollup is the way to go.

**Pull request closed without merging**
