### PR TITLE
Add additional exports for ThreeVector and Quaternion.

### PR DESCRIPTION
**Pull request by alexanderson1993**

### CODE REVIEW

**Comment by namel** [comment]
This is a good pull request.  I'd be happy to accept it - but it currently has conflicts (due to dist files which have changed).  Can you rebase, overwriting the dist files?

**Comment by alexanderson1993** [comment]
I've updated the branch. I'm afraid I didn't rebase properly, but you should be able to rebase my changes onto the original repo when you merge the PR.

Thanks!

**Comment by namel** [comment]
hi @alexanderson1993 github does not allow me to rebase and merge in this PR, because it doesn't know how to handle the conflicts.  

This is actually my fault, because I checked in the dist directory.  

I removed the contents of the dist subdirectories now, leaving them empty and the contents git-ignored.

Can you create a new PR, which is based on the latest master version?  it doesn't need to include the build outputs any more.

**Comment by alexanderson1993** [comment]
Yeah, let me do that.

**Pull request closed without merging**
